ci fixes

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -32,7 +32,11 @@ jobs:
           chmod -R 777 allure-report
 
       - name: Generate Allure report inside container
-        run: docker compose run --rm allure_service
+        #        run: docker compose run --rm allure_service
+        run: docker compose up allure_service
+
+      - name: Check allure-report content
+        run: ls -R allure-report || echo "allure-report folder is empty or not found"
 
       - name: Upload Allure report artifact
         uses: actions/upload-artifact@v4
